import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="es">
        <body>
          <div className="ml-auto mb-6 w-screen">{children}</div>
        </body>
      </html>
    </AuthProvider>
  );
}
